name: Python
on:
  [push]
jobs:
  test:
    env:
      TELNYX_MOCK_VERSION: 0.8.10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, pypy-2.7, pypy-3.6]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: dschep/install-pipenv-action@v1
      - name: setup-telnyx-mock
        run: source ./.github/scripts/before_install.sh
      - name: init
        run: make init
      - name: lint
        run: source ./.github/scripts/lint.sh
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
      - name: ci
        run: make ci
      - name: coveralls
        run: make coveralls

