name: Python
on:
  [push]
jobs:
  test:
    env:
      TELNYX_MOCK_VERSION: 0.8.10
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - python-version: 2.7
         - python-version: 3.4
         - python-version: 3.5
         - python-version: 3.6
         - python-version: 3.7
         - python-version: 3.8-dev
         - python-version: nightly
         - python-version: pypy2.7-6.0
         - python-version: pypy3.5-6.0
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup-telnyx-mock
        run: source ./.github/scripts/before_install.sh
      - name: init
        run: make init
      - name: lint
        run: source ./.github/scripts/lint.sh
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
      - name: ci
        run: make ci
      - name: coveralls
        run: make coveralls

